DROP SEQUENCE PRODUCT_SEQ IF EXISTS;
DROP TABLE PRODUCT IF EXISTS;
CREATE SEQUENCE PRODUCT_SEQ START WITH 1;
CREATE TABLE PRODUCT (
    ID NUMERIC(8) NOT NULL
    , NAME VARCHAR2(255) 
    , DESCRIPTION VARCHAR2(500) 
    , CATEGORY VARCHAR2(255)
    , PRICE DECIMAL NOT NULL
    , PRIMARY KEY (ID)
);

DROP SEQUENCE ORDER_SEQ IF EXISTS;
DROP TABLE ORDERS IF EXISTS;
CREATE SEQUENCE ORDER_SEQ START WITH 1;
CREATE TABLE ORDERS (
    ID NUMERIC(8) NOT NULL
    , NAME VARCHAR2(255) 
    , STREET VARCHAR2(255) 
    , CITY VARCHAR2(255)
    , STATE VARCHAR2(255) 
    , ZIP VARCHAR2(255) 
    , COUNTRY VARCHAR2(255)
    , PRIMARY KEY (ID)
);

DROP SEQUENCE ORDER_DETAIL_SEQ IF EXISTS;
DROP TABLE ORDER_DETAIL IF EXISTS;
CREATE SEQUENCE ORDER_DETAIL_SEQ START WITH 1;
CREATE TABLE ORDER_DETAIL (
    ID NUMERIC(8) NOT NULL
    , ORDER_ID NUMERIC(8) NOT NULL 
    , NAME VARCHAR2(255)
    , PRICE DECIMAL
    , QUANTITY NUMERIC(8) NOT NULL
    , PRIMARY KEY (ID)
    , FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
);

